export class UserActionTypes {
  static SET_CURRENT_USER = "SET_CURRENT_USER";
  static CHECK_USER_SESSION = "CHECK_USER_SESSION";
  static GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
  static EMAIL_SIGN_IN_START = "EMAIL_SIGN_IN_START";
  static SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
  static SIGN_IN_FAILED = "SIGN_IN_FAILED";
  static SIGN_UP_START = "SIGN_UP_START";
  static SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
  static SIGN_UP_FAILED = "SIGN_UP_FAILED";
}
